name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .vuepress/dist # 빌드된 결과물이 저장되는 폴더
          branch: gh-pages # 배포된 파일이 담길 브랜치
